### ISSUE TITLE
Share buttons are unreliable

### ISSUE THREAD

**Issue by xuther** [byuoitav/touchpanel-ui-microservice#289] opened 2017-12-22 17:19 UTC
The buttons to select displays to share to have issues being pressed on the panels. I have a video available.

**Comment by dannyrandall** [comment] 2018-01-01 19:54
This was being caused by an array not being cleared of the selected displays. Now, every time the share popup is opened, that array is cleared and repopulated; The buttons work correctly following that fix. I can't find the commit where it was fixed, but I'll just close this issue.

**Closed by dannyrandall** 2018-01-01 19:54 UTC
Labels: bug
